all_questions = [
    "What’s something new you’ve learned about yourself in the last three months?",
    "If you had to describe how you’re feeling right now as an amusement park ride, what ride are you on?",
    "How would you describe your communication style in three words?",
    "How do you recognize when you’re stressed?",
    "If you were coming out onto a stage, what would your entrance theme song be?",
    "If you could bring back a fashion trend, what would it be and why?",
    "If you could live in another historical period, would you? If so, which one?",
    "If you were reincarnated as an animal, what would you choose and why?",
    "What’s one thing you are unbeatable at?",
    "How would you spend your days if you had unlimited time and resources?",
    "How do you get motivated for difficult tasks?",
    "What’s something on your desk, a nearby wall, or out the window that cheers you up during the day?",
    "Do you have any mentors or people you look up to? Tell us about one of them.",
    "What fictional world or place would you like to visit?",
    "You’ve been teleported to the Middle Ages. How would you make a living there?",
    "Suppose you were going to be frozen tomorrow for a one-way 1,000-year interstellar voyage. What would you most want to communicate (and to whom) before you leave?",
    "If you could have an animal sidekick, what would it be? Why?",
    "What looks easy-peasy lemon squeezy but is actually difficult difficult lemon difficult?",
    "You’ve died, but instead of entering the afterlife, you’ve entered Earth 2.0. What are some things that make Earth 2.0 better?",
    "If you could go back in time 10,000 years ago and make a cave painting to confuse everyone in the future, what would you draw?",
    "A genie appears and grants you a wish for someone else in the world. Who and what do you make a wish for?",
    "If you had a magic button on your desk to bring you whatever you wanted, what would it summon?",
    "What’s the last thing you did for the first time?",
    "What smell, image, or sound triggers nostalgia for you?",
    "What’s one thing your parents or guardians constantly nagged you about?",
    "Tell us about a stranger you still remember. What made them memorable?",
    "What ice cream flavor sums up your personality today?",
    "You’ve been granted a one-way ticket to another country of your choice. Where are you going?",
    "What’s something you’ve drawn inspiration from recently?",
    "It’s your first day on the job as an evil villain. What’s the first piece of mischief you commit?",
    "If buying groceries were a game, what would one of the loading screen tips be?",
    "What animal best represents you today and why?",
    "If you could have one superpower today, what would it be, and what would you use it for?",
    "What thing from nature, excluding animals, best describes you today?",
    "If you had to sing karaoke right now, which song would you pick?",
    "What is the most used emoji on your phone right now?",
    "What was the first thing you thought about when you woke up today?",
    "Which do you prefer, oceans or mountains? Why?",
    "What’s one of your favorite recent memories?",
    "What’s the best phrase or piece of slang people in your hometown use?",
    "What’s your guilty pleasure right now?",
    "What book would you like to live in?",
    "If you could be famous for one thing, what would it be?",
    "What’s a word or phrase in another language (or your own) that you really like?",
    "What’s the best topping for ice cream?",
    "If you’re at trivia night, what category would you know most about?",
    "What’s an album you recommend that has no bad songs?",
    "What’s the worst haircut you ever had?",
    "What’s an obscure TV show or movie that everyone should watch?",
    "If you had to describe how you’re feeling right now as a weather pattern, what’s your forecast?",
    "What’s an under-rated skill everyone can benefit from?",
    "What’s something you’re worried about (professionally)?",
    "What’s got your attention today and why?",
    "What was your favorite recent book or article, and what did it inspire?",
    "Heard any good tips lately?",
    "What color best describes your personality today?",
    "What’s one project you could stop doing to give yourself more focus?",
    "What are you excited about this week?",
    "Do you have any routines you use to improve your energy and focus?",
    "What’s one thing you wish could be automated in your job?",
    "What’s one thing you’ve been procrastinating on and can’t finish?",
    "What’s the last thing you completed that you’re proud of?",
    "Have you learned any useful productivity hacks recently?",
    "What’s one productivity tool you couldn’t live without, and what makes it indispensable?",
    "What’s one recent thing or experience that exceeded your expectations?",
    "What are you grateful for today?",
    "What’s something that made you smile recently?",
    "What fruit or vegetable represents your mood today?",
    "What small thing would improve your day today?",
    "What’s something that puts you in a state of flow?",
    "What’s one possession or tool that enhances your daily life?",
    "What’s a simple life hack that everyone can benefit from?",
    "What’s one of the best ideas our company has come up with?",
    "What’s something you want to get better at?",
    "What’s your favorite song or soundtrack for doing focused work?",
    "What emoji represents you today and why?",
    "If you could be one other person, who would that person be and why?",
    "If you could safely eat any inedible object, what would it be?",
    "If you could pick up a new skill in an instant, what would it be?",
    "What’s something people don’t know about you?",
    "What’s the most useful item you’ve purchased this year?",
    "What’s the worst piece of advice you’ve ever been given? And why was it so bad?",
    "If you could teleport anywhere, where would you go right now?",
    "What’s the last book you quit reading and why?",
    "If you could be fluent in another language instantly, which would you choose and why?",
    "Name a TV show you think is underrated. Describe it in a sentence.",
    "What’s the next item on your bucket list?",
    "What’s your guilty pleasure when you have free time during the week?",
    "What’s your favorite thing about the place where you live?",
    "What’s a hobby or side project you’ve been meaning to take up?",
    "What do your family or other loved ones think you do for work?",
    "When you’re packing for a trip, what’s one thing (other than clothes) you always bring?",
    "If you had to put together a PowerPoint presentation about anything, what would it be about?",
    "What profession did you have in a previous life?",
    "What flavor of tea represents you today?",
    "What would you do if you had a fully paid year-long break from work?",
    "What’s the worst job you ever had?",
    "If you did not have to sleep, how would you spend the extra eight hours?",
    "What fictional world would you most like to live in?",
    "If you could live with any fictional character, who would you choose?",
    "What is your favorite smell and why?",
    "If you could describe your life as a movie, what genre would it be?",
    "Name a healthy food you enjoy and an unhealthy one you find hard to resist.",
    "What age do you wish you could be permanently?",
    "If you were forced to watch reruns of a favorite show, which would you choose?",
    "Would you rather take a cold shower every day or always sleep an hour less than you need?",
    "What drink best describes you today?",
    "If you had to eat only one dish for the rest of time, what would it be?",
    "What current fact about your life would most impress your five-year-old self?",
    "What’s something you are craving right now?",
    "What healthy food tastes just as good to you as unhealthy food?",
    "What’s an unusual skill you’d love to master?",
    "You’re on a desert island and can bring one luxury with you – what is it?",
    "What’s a sauce, condiment, or dressing you couldn’t live without?",
    "What’s something you like to do whenever you travel to a new country?",
    "How would your best friend describe you?",
    "What is something you will never eat, no matter how hungry you get?",
    "If you were on a reality show, what would be your catchphrase?",
    "What’s the title of a podcast you would never listen to?",
    "If you were an action figure, what two accessories would you come with?",
    "What question would you ask a psychic?",
    "What’s the best present someone could bring to your housewarming party?",
    "You can be reincarnated for a day as any living or historical famous person. Who do you choose and why?",
    "What’s something that always gives you child-like joy?",
    "What’s your culture’s most underrated food?",
    "If people came with a warning tag, what would yours be?",
    "If you were a kitchen utensil, which one would you be and why?",
    "What would the title of your autobiography be?"
]